// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

#ifndef PROTOBUF_auth_2eproto__INCLUDED
#define PROTOBUF_auth_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace zproto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_auth_2eproto();
void protobuf_AssignDesc_auth_2eproto();
void protobuf_ShutdownFile_auth_2eproto();

class AuthRsp;
class ClientOfflineReq;
class ClientOfflineRsp;
class ClientOnlineReq;
class ClientOnlineRsp;
class TokenAuthReq;

// ===================================================================

class TokenAuthReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.TokenAuthReq) */ {
 public:
  TokenAuthReq();
  virtual ~TokenAuthReq();

  TokenAuthReq(const TokenAuthReq& from);

  inline TokenAuthReq& operator=(const TokenAuthReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TokenAuthReq& default_instance();

  void Swap(TokenAuthReq* other);

  // implements Message ----------------------------------------------

  inline TokenAuthReq* New() const { return New(NULL); }

  TokenAuthReq* New(::google::protobuf::Arena* arena) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TokenAuthReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 app_key = 1;
  void clear_app_key();
  static const int kAppKeyFieldNumber = 1;
  ::google::protobuf::int32 app_key() const;
  void set_app_key(::google::protobuf::int32 value);

  // optional string app_token = 2;
  void clear_app_token();
  static const int kAppTokenFieldNumber = 2;
  const ::std::string& app_token() const;
  void set_app_token(const ::std::string& value);
  void set_app_token(const char* value);
  void set_app_token(const char* value, size_t size);
  ::std::string* mutable_app_token();
  ::std::string* release_app_token();
  void set_allocated_app_token(::std::string* app_token);

  // optional bytes device_hash = 3;
  void clear_device_hash();
  static const int kDeviceHashFieldNumber = 3;
  const ::std::string& device_hash() const;
  void set_device_hash(const ::std::string& value);
  void set_device_hash(const char* value);
  void set_device_hash(const void* value, size_t size);
  ::std::string* mutable_device_hash();
  ::std::string* release_device_hash();
  void set_allocated_device_hash(::std::string* device_hash);

  // optional string device_title = 4;
  void clear_device_title();
  static const int kDeviceTitleFieldNumber = 4;
  const ::std::string& device_title() const;
  void set_device_title(const ::std::string& value);
  void set_device_title(const char* value);
  void set_device_title(const char* value, size_t size);
  ::std::string* mutable_device_title();
  ::std::string* release_device_title();
  void set_allocated_device_title(::std::string* device_title);

  // optional string time_zone = 5;
  void clear_time_zone();
  static const int kTimeZoneFieldNumber = 5;
  const ::std::string& time_zone() const;
  void set_time_zone(const ::std::string& value);
  void set_time_zone(const char* value);
  void set_time_zone(const char* value, size_t size);
  ::std::string* mutable_time_zone();
  ::std::string* release_time_zone();
  void set_allocated_time_zone(::std::string* time_zone);

  // @@protoc_insertion_point(class_scope:zproto.TokenAuthReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr app_token_;
  ::google::protobuf::internal::ArenaStringPtr device_hash_;
  ::google::protobuf::internal::ArenaStringPtr device_title_;
  ::google::protobuf::internal::ArenaStringPtr time_zone_;
  ::google::protobuf::int32 app_key_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_auth_2eproto();
  friend void protobuf_AssignDesc_auth_2eproto();
  friend void protobuf_ShutdownFile_auth_2eproto();

  void InitAsDefaultInstance();
  static TokenAuthReq* default_instance_;
};
// -------------------------------------------------------------------

class AuthRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.AuthRsp) */ {
 public:
  AuthRsp();
  virtual ~AuthRsp();

  AuthRsp(const AuthRsp& from);

  inline AuthRsp& operator=(const AuthRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthRsp& default_instance();

  void Swap(AuthRsp* other);

  // implements Message ----------------------------------------------

  inline AuthRsp* New() const { return New(NULL); }

  AuthRsp* New(::google::protobuf::Arena* arena) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AuthRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string user_id = 2;
  void clear_user_id();
  static const int kUserIdFieldNumber = 2;
  const ::std::string& user_id() const;
  void set_user_id(const ::std::string& value);
  void set_user_id(const char* value);
  void set_user_id(const char* value, size_t size);
  ::std::string* mutable_user_id();
  ::std::string* release_user_id();
  void set_allocated_user_id(::std::string* user_id);

  // @@protoc_insertion_point(class_scope:zproto.AuthRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr user_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_auth_2eproto();
  friend void protobuf_AssignDesc_auth_2eproto();
  friend void protobuf_ShutdownFile_auth_2eproto();

  void InitAsDefaultInstance();
  static AuthRsp* default_instance_;
};
// -------------------------------------------------------------------

class ClientOnlineReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.ClientOnlineReq) */ {
 public:
  ClientOnlineReq();
  virtual ~ClientOnlineReq();

  ClientOnlineReq(const ClientOnlineReq& from);

  inline ClientOnlineReq& operator=(const ClientOnlineReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientOnlineReq& default_instance();

  void Swap(ClientOnlineReq* other);

  // implements Message ----------------------------------------------

  inline ClientOnlineReq* New() const { return New(NULL); }

  ClientOnlineReq* New(::google::protobuf::Arena* arena) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ClientOnlineReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 server_id = 1;
  void clear_server_id();
  static const int kServerIdFieldNumber = 1;
  ::google::protobuf::uint32 server_id() const;
  void set_server_id(::google::protobuf::uint32 value);

  // optional uint64 conn_id = 2;
  void clear_conn_id();
  static const int kConnIdFieldNumber = 2;
  ::google::protobuf::uint64 conn_id() const;
  void set_conn_id(::google::protobuf::uint64 value);

  // optional uint32 app_id = 3;
  void clear_app_id();
  static const int kAppIdFieldNumber = 3;
  ::google::protobuf::uint32 app_id() const;
  void set_app_id(::google::protobuf::uint32 value);

  // optional uint32 user_id = 4;
  void clear_user_id();
  static const int kUserIdFieldNumber = 4;
  ::google::protobuf::uint32 user_id() const;
  void set_user_id(::google::protobuf::uint32 value);

  // optional uint32 state = 5;
  void clear_state();
  static const int kStateFieldNumber = 5;
  ::google::protobuf::uint32 state() const;
  void set_state(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:zproto.ClientOnlineReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 conn_id_;
  ::google::protobuf::uint32 server_id_;
  ::google::protobuf::uint32 app_id_;
  ::google::protobuf::uint32 user_id_;
  ::google::protobuf::uint32 state_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_auth_2eproto();
  friend void protobuf_AssignDesc_auth_2eproto();
  friend void protobuf_ShutdownFile_auth_2eproto();

  void InitAsDefaultInstance();
  static ClientOnlineReq* default_instance_;
};
// -------------------------------------------------------------------

class ClientOnlineRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.ClientOnlineRsp) */ {
 public:
  ClientOnlineRsp();
  virtual ~ClientOnlineRsp();

  ClientOnlineRsp(const ClientOnlineRsp& from);

  inline ClientOnlineRsp& operator=(const ClientOnlineRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientOnlineRsp& default_instance();

  void Swap(ClientOnlineRsp* other);

  // implements Message ----------------------------------------------

  inline ClientOnlineRsp* New() const { return New(NULL); }

  ClientOnlineRsp* New(::google::protobuf::Arena* arena) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ClientOnlineRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 index_id = 1;
  void clear_index_id();
  static const int kIndexIdFieldNumber = 1;
  ::google::protobuf::uint64 index_id() const;
  void set_index_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:zproto.ClientOnlineRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 index_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_auth_2eproto();
  friend void protobuf_AssignDesc_auth_2eproto();
  friend void protobuf_ShutdownFile_auth_2eproto();

  void InitAsDefaultInstance();
  static ClientOnlineRsp* default_instance_;
};
// -------------------------------------------------------------------

class ClientOfflineReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.ClientOfflineReq) */ {
 public:
  ClientOfflineReq();
  virtual ~ClientOfflineReq();

  ClientOfflineReq(const ClientOfflineReq& from);

  inline ClientOfflineReq& operator=(const ClientOfflineReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientOfflineReq& default_instance();

  void Swap(ClientOfflineReq* other);

  // implements Message ----------------------------------------------

  inline ClientOfflineReq* New() const { return New(NULL); }

  ClientOfflineReq* New(::google::protobuf::Arena* arena) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ClientOfflineReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 server_id = 1;
  void clear_server_id();
  static const int kServerIdFieldNumber = 1;
  ::google::protobuf::uint32 server_id() const;
  void set_server_id(::google::protobuf::uint32 value);

  // optional uint64 conn_id = 2;
  void clear_conn_id();
  static const int kConnIdFieldNumber = 2;
  ::google::protobuf::uint64 conn_id() const;
  void set_conn_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:zproto.ClientOfflineReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 conn_id_;
  ::google::protobuf::uint32 server_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_auth_2eproto();
  friend void protobuf_AssignDesc_auth_2eproto();
  friend void protobuf_ShutdownFile_auth_2eproto();

  void InitAsDefaultInstance();
  static ClientOfflineReq* default_instance_;
};
// -------------------------------------------------------------------

class ClientOfflineRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.ClientOfflineRsp) */ {
 public:
  ClientOfflineRsp();
  virtual ~ClientOfflineRsp();

  ClientOfflineRsp(const ClientOfflineRsp& from);

  inline ClientOfflineRsp& operator=(const ClientOfflineRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientOfflineRsp& default_instance();

  void Swap(ClientOfflineRsp* other);

  // implements Message ----------------------------------------------

  inline ClientOfflineRsp* New() const { return New(NULL); }

  ClientOfflineRsp* New(::google::protobuf::Arena* arena) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ClientOfflineRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 index_id = 1;
  void clear_index_id();
  static const int kIndexIdFieldNumber = 1;
  ::google::protobuf::uint64 index_id() const;
  void set_index_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:zproto.ClientOfflineRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 index_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_auth_2eproto();
  friend void protobuf_AssignDesc_auth_2eproto();
  friend void protobuf_ShutdownFile_auth_2eproto();

  void InitAsDefaultInstance();
  static ClientOfflineRsp* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// TokenAuthReq

// optional int32 app_key = 1;
inline void TokenAuthReq::clear_app_key() {
  app_key_ = 0;
}
inline ::google::protobuf::int32 TokenAuthReq::app_key() const {
  // @@protoc_insertion_point(field_get:zproto.TokenAuthReq.app_key)
  return app_key_;
}
inline void TokenAuthReq::set_app_key(::google::protobuf::int32 value) {
  
  app_key_ = value;
  // @@protoc_insertion_point(field_set:zproto.TokenAuthReq.app_key)
}

// optional string app_token = 2;
inline void TokenAuthReq::clear_app_token() {
  app_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TokenAuthReq::app_token() const {
  // @@protoc_insertion_point(field_get:zproto.TokenAuthReq.app_token)
  return app_token_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TokenAuthReq::set_app_token(const ::std::string& value) {
  
  app_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.TokenAuthReq.app_token)
}
inline void TokenAuthReq::set_app_token(const char* value) {
  
  app_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.TokenAuthReq.app_token)
}
inline void TokenAuthReq::set_app_token(const char* value, size_t size) {
  
  app_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.TokenAuthReq.app_token)
}
inline ::std::string* TokenAuthReq::mutable_app_token() {
  
  // @@protoc_insertion_point(field_mutable:zproto.TokenAuthReq.app_token)
  return app_token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TokenAuthReq::release_app_token() {
  // @@protoc_insertion_point(field_release:zproto.TokenAuthReq.app_token)
  
  return app_token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TokenAuthReq::set_allocated_app_token(::std::string* app_token) {
  if (app_token != NULL) {
    
  } else {
    
  }
  app_token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), app_token);
  // @@protoc_insertion_point(field_set_allocated:zproto.TokenAuthReq.app_token)
}

// optional bytes device_hash = 3;
inline void TokenAuthReq::clear_device_hash() {
  device_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TokenAuthReq::device_hash() const {
  // @@protoc_insertion_point(field_get:zproto.TokenAuthReq.device_hash)
  return device_hash_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TokenAuthReq::set_device_hash(const ::std::string& value) {
  
  device_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.TokenAuthReq.device_hash)
}
inline void TokenAuthReq::set_device_hash(const char* value) {
  
  device_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.TokenAuthReq.device_hash)
}
inline void TokenAuthReq::set_device_hash(const void* value, size_t size) {
  
  device_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.TokenAuthReq.device_hash)
}
inline ::std::string* TokenAuthReq::mutable_device_hash() {
  
  // @@protoc_insertion_point(field_mutable:zproto.TokenAuthReq.device_hash)
  return device_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TokenAuthReq::release_device_hash() {
  // @@protoc_insertion_point(field_release:zproto.TokenAuthReq.device_hash)
  
  return device_hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TokenAuthReq::set_allocated_device_hash(::std::string* device_hash) {
  if (device_hash != NULL) {
    
  } else {
    
  }
  device_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_hash);
  // @@protoc_insertion_point(field_set_allocated:zproto.TokenAuthReq.device_hash)
}

// optional string device_title = 4;
inline void TokenAuthReq::clear_device_title() {
  device_title_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TokenAuthReq::device_title() const {
  // @@protoc_insertion_point(field_get:zproto.TokenAuthReq.device_title)
  return device_title_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TokenAuthReq::set_device_title(const ::std::string& value) {
  
  device_title_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.TokenAuthReq.device_title)
}
inline void TokenAuthReq::set_device_title(const char* value) {
  
  device_title_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.TokenAuthReq.device_title)
}
inline void TokenAuthReq::set_device_title(const char* value, size_t size) {
  
  device_title_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.TokenAuthReq.device_title)
}
inline ::std::string* TokenAuthReq::mutable_device_title() {
  
  // @@protoc_insertion_point(field_mutable:zproto.TokenAuthReq.device_title)
  return device_title_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TokenAuthReq::release_device_title() {
  // @@protoc_insertion_point(field_release:zproto.TokenAuthReq.device_title)
  
  return device_title_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TokenAuthReq::set_allocated_device_title(::std::string* device_title) {
  if (device_title != NULL) {
    
  } else {
    
  }
  device_title_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_title);
  // @@protoc_insertion_point(field_set_allocated:zproto.TokenAuthReq.device_title)
}

// optional string time_zone = 5;
inline void TokenAuthReq::clear_time_zone() {
  time_zone_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TokenAuthReq::time_zone() const {
  // @@protoc_insertion_point(field_get:zproto.TokenAuthReq.time_zone)
  return time_zone_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TokenAuthReq::set_time_zone(const ::std::string& value) {
  
  time_zone_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.TokenAuthReq.time_zone)
}
inline void TokenAuthReq::set_time_zone(const char* value) {
  
  time_zone_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.TokenAuthReq.time_zone)
}
inline void TokenAuthReq::set_time_zone(const char* value, size_t size) {
  
  time_zone_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.TokenAuthReq.time_zone)
}
inline ::std::string* TokenAuthReq::mutable_time_zone() {
  
  // @@protoc_insertion_point(field_mutable:zproto.TokenAuthReq.time_zone)
  return time_zone_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TokenAuthReq::release_time_zone() {
  // @@protoc_insertion_point(field_release:zproto.TokenAuthReq.time_zone)
  
  return time_zone_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TokenAuthReq::set_allocated_time_zone(::std::string* time_zone) {
  if (time_zone != NULL) {
    
  } else {
    
  }
  time_zone_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), time_zone);
  // @@protoc_insertion_point(field_set_allocated:zproto.TokenAuthReq.time_zone)
}

// -------------------------------------------------------------------

// AuthRsp

// optional string user_id = 2;
inline void AuthRsp::clear_user_id() {
  user_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AuthRsp::user_id() const {
  // @@protoc_insertion_point(field_get:zproto.AuthRsp.user_id)
  return user_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AuthRsp::set_user_id(const ::std::string& value) {
  
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.AuthRsp.user_id)
}
inline void AuthRsp::set_user_id(const char* value) {
  
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.AuthRsp.user_id)
}
inline void AuthRsp::set_user_id(const char* value, size_t size) {
  
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.AuthRsp.user_id)
}
inline ::std::string* AuthRsp::mutable_user_id() {
  
  // @@protoc_insertion_point(field_mutable:zproto.AuthRsp.user_id)
  return user_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AuthRsp::release_user_id() {
  // @@protoc_insertion_point(field_release:zproto.AuthRsp.user_id)
  
  return user_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AuthRsp::set_allocated_user_id(::std::string* user_id) {
  if (user_id != NULL) {
    
  } else {
    
  }
  user_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_id);
  // @@protoc_insertion_point(field_set_allocated:zproto.AuthRsp.user_id)
}

// -------------------------------------------------------------------

// ClientOnlineReq

// optional uint32 server_id = 1;
inline void ClientOnlineReq::clear_server_id() {
  server_id_ = 0u;
}
inline ::google::protobuf::uint32 ClientOnlineReq::server_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOnlineReq.server_id)
  return server_id_;
}
inline void ClientOnlineReq::set_server_id(::google::protobuf::uint32 value) {
  
  server_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOnlineReq.server_id)
}

// optional uint64 conn_id = 2;
inline void ClientOnlineReq::clear_conn_id() {
  conn_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ClientOnlineReq::conn_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOnlineReq.conn_id)
  return conn_id_;
}
inline void ClientOnlineReq::set_conn_id(::google::protobuf::uint64 value) {
  
  conn_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOnlineReq.conn_id)
}

// optional uint32 app_id = 3;
inline void ClientOnlineReq::clear_app_id() {
  app_id_ = 0u;
}
inline ::google::protobuf::uint32 ClientOnlineReq::app_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOnlineReq.app_id)
  return app_id_;
}
inline void ClientOnlineReq::set_app_id(::google::protobuf::uint32 value) {
  
  app_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOnlineReq.app_id)
}

// optional uint32 user_id = 4;
inline void ClientOnlineReq::clear_user_id() {
  user_id_ = 0u;
}
inline ::google::protobuf::uint32 ClientOnlineReq::user_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOnlineReq.user_id)
  return user_id_;
}
inline void ClientOnlineReq::set_user_id(::google::protobuf::uint32 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOnlineReq.user_id)
}

// optional uint32 state = 5;
inline void ClientOnlineReq::clear_state() {
  state_ = 0u;
}
inline ::google::protobuf::uint32 ClientOnlineReq::state() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOnlineReq.state)
  return state_;
}
inline void ClientOnlineReq::set_state(::google::protobuf::uint32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOnlineReq.state)
}

// -------------------------------------------------------------------

// ClientOnlineRsp

// optional uint64 index_id = 1;
inline void ClientOnlineRsp::clear_index_id() {
  index_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ClientOnlineRsp::index_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOnlineRsp.index_id)
  return index_id_;
}
inline void ClientOnlineRsp::set_index_id(::google::protobuf::uint64 value) {
  
  index_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOnlineRsp.index_id)
}

// -------------------------------------------------------------------

// ClientOfflineReq

// optional uint32 server_id = 1;
inline void ClientOfflineReq::clear_server_id() {
  server_id_ = 0u;
}
inline ::google::protobuf::uint32 ClientOfflineReq::server_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOfflineReq.server_id)
  return server_id_;
}
inline void ClientOfflineReq::set_server_id(::google::protobuf::uint32 value) {
  
  server_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOfflineReq.server_id)
}

// optional uint64 conn_id = 2;
inline void ClientOfflineReq::clear_conn_id() {
  conn_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ClientOfflineReq::conn_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOfflineReq.conn_id)
  return conn_id_;
}
inline void ClientOfflineReq::set_conn_id(::google::protobuf::uint64 value) {
  
  conn_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOfflineReq.conn_id)
}

// -------------------------------------------------------------------

// ClientOfflineRsp

// optional uint64 index_id = 1;
inline void ClientOfflineRsp::clear_index_id() {
  index_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ClientOfflineRsp::index_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOfflineRsp.index_id)
  return index_id_;
}
inline void ClientOfflineRsp::set_index_id(::google::protobuf::uint64 value) {
  
  index_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOfflineRsp.index_id)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace zproto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_auth_2eproto__INCLUDED
