// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "auth.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace zproto {

namespace {

const ::google::protobuf::Descriptor* TokenAuthReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TokenAuthReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* AuthRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AuthRsp_reflection_ = NULL;
const ::google::protobuf::Descriptor* ClientOnlineReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClientOnlineReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* ClientOnlineRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClientOnlineRsp_reflection_ = NULL;
const ::google::protobuf::Descriptor* ClientOfflineReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClientOfflineReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* ClientOfflineRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClientOfflineRsp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_auth_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_auth_2eproto() {
  protobuf_AddDesc_auth_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "auth.proto");
  GOOGLE_CHECK(file != NULL);
  TokenAuthReq_descriptor_ = file->message_type(0);
  static const int TokenAuthReq_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenAuthReq, app_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenAuthReq, app_token_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenAuthReq, device_hash_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenAuthReq, device_title_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenAuthReq, time_zone_),
  };
  TokenAuthReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TokenAuthReq_descriptor_,
      TokenAuthReq::default_instance_,
      TokenAuthReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(TokenAuthReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenAuthReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TokenAuthReq, _is_default_instance_));
  AuthRsp_descriptor_ = file->message_type(1);
  static const int AuthRsp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AuthRsp, user_id_),
  };
  AuthRsp_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      AuthRsp_descriptor_,
      AuthRsp::default_instance_,
      AuthRsp_offsets_,
      -1,
      -1,
      -1,
      sizeof(AuthRsp),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AuthRsp, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AuthRsp, _is_default_instance_));
  ClientOnlineReq_descriptor_ = file->message_type(2);
  static const int ClientOnlineReq_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOnlineReq, server_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOnlineReq, conn_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOnlineReq, app_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOnlineReq, user_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOnlineReq, state_),
  };
  ClientOnlineReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ClientOnlineReq_descriptor_,
      ClientOnlineReq::default_instance_,
      ClientOnlineReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(ClientOnlineReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOnlineReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOnlineReq, _is_default_instance_));
  ClientOnlineRsp_descriptor_ = file->message_type(3);
  static const int ClientOnlineRsp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOnlineRsp, index_id_),
  };
  ClientOnlineRsp_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ClientOnlineRsp_descriptor_,
      ClientOnlineRsp::default_instance_,
      ClientOnlineRsp_offsets_,
      -1,
      -1,
      -1,
      sizeof(ClientOnlineRsp),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOnlineRsp, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOnlineRsp, _is_default_instance_));
  ClientOfflineReq_descriptor_ = file->message_type(4);
  static const int ClientOfflineReq_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOfflineReq, server_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOfflineReq, conn_id_),
  };
  ClientOfflineReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ClientOfflineReq_descriptor_,
      ClientOfflineReq::default_instance_,
      ClientOfflineReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(ClientOfflineReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOfflineReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOfflineReq, _is_default_instance_));
  ClientOfflineRsp_descriptor_ = file->message_type(5);
  static const int ClientOfflineRsp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOfflineRsp, index_id_),
  };
  ClientOfflineRsp_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ClientOfflineRsp_descriptor_,
      ClientOfflineRsp::default_instance_,
      ClientOfflineRsp_offsets_,
      -1,
      -1,
      -1,
      sizeof(ClientOfflineRsp),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOfflineRsp, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientOfflineRsp, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_auth_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TokenAuthReq_descriptor_, &TokenAuthReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      AuthRsp_descriptor_, &AuthRsp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ClientOnlineReq_descriptor_, &ClientOnlineReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ClientOnlineRsp_descriptor_, &ClientOnlineRsp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ClientOfflineReq_descriptor_, &ClientOfflineReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ClientOfflineRsp_descriptor_, &ClientOfflineRsp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_auth_2eproto() {
  delete TokenAuthReq::default_instance_;
  delete TokenAuthReq_reflection_;
  delete AuthRsp::default_instance_;
  delete AuthRsp_reflection_;
  delete ClientOnlineReq::default_instance_;
  delete ClientOnlineReq_reflection_;
  delete ClientOnlineRsp::default_instance_;
  delete ClientOnlineRsp_reflection_;
  delete ClientOfflineReq::default_instance_;
  delete ClientOfflineReq_reflection_;
  delete ClientOfflineRsp::default_instance_;
  delete ClientOfflineRsp_reflection_;
}

void protobuf_AddDesc_auth_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_auth_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nauth.proto\022\006zproto\"p\n\014TokenAuthReq\022\017\n\007"
    "app_key\030\001 \001(\005\022\021\n\tapp_token\030\002 \001(\t\022\023\n\013devi"
    "ce_hash\030\003 \001(\014\022\024\n\014device_title\030\004 \001(\t\022\021\n\tt"
    "ime_zone\030\005 \001(\t\"\032\n\007AuthRsp\022\017\n\007user_id\030\002 \001"
    "(\t\"e\n\017ClientOnlineReq\022\021\n\tserver_id\030\001 \001(\r"
    "\022\017\n\007conn_id\030\002 \001(\004\022\016\n\006app_id\030\003 \001(\r\022\017\n\007use"
    "r_id\030\004 \001(\r\022\r\n\005state\030\005 \001(\r\"#\n\017ClientOnlin"
    "eRsp\022\020\n\010index_id\030\001 \001(\004\"6\n\020ClientOfflineR"
    "eq\022\021\n\tserver_id\030\001 \001(\r\022\017\n\007conn_id\030\002 \001(\004\"$"
    "\n\020ClientOfflineRsp\022\020\n\010index_id\030\001 \001(\004B\'\n\027"
    "com.zchat.engine.zprotoB\nZProtoAuthH\002b\006p"
    "roto3", 445);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "auth.proto", &protobuf_RegisterTypes);
  TokenAuthReq::default_instance_ = new TokenAuthReq();
  AuthRsp::default_instance_ = new AuthRsp();
  ClientOnlineReq::default_instance_ = new ClientOnlineReq();
  ClientOnlineRsp::default_instance_ = new ClientOnlineRsp();
  ClientOfflineReq::default_instance_ = new ClientOfflineReq();
  ClientOfflineRsp::default_instance_ = new ClientOfflineRsp();
  TokenAuthReq::default_instance_->InitAsDefaultInstance();
  AuthRsp::default_instance_->InitAsDefaultInstance();
  ClientOnlineReq::default_instance_->InitAsDefaultInstance();
  ClientOnlineRsp::default_instance_->InitAsDefaultInstance();
  ClientOfflineReq::default_instance_->InitAsDefaultInstance();
  ClientOfflineRsp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_auth_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_auth_2eproto {
  StaticDescriptorInitializer_auth_2eproto() {
    protobuf_AddDesc_auth_2eproto();
  }
} static_descriptor_initializer_auth_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TokenAuthReq::kAppKeyFieldNumber;
const int TokenAuthReq::kAppTokenFieldNumber;
const int TokenAuthReq::kDeviceHashFieldNumber;
const int TokenAuthReq::kDeviceTitleFieldNumber;
const int TokenAuthReq::kTimeZoneFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TokenAuthReq::TokenAuthReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.TokenAuthReq)
}

void TokenAuthReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

TokenAuthReq::TokenAuthReq(const TokenAuthReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.TokenAuthReq)
}

void TokenAuthReq::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  app_key_ = 0;
  app_token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  device_hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  device_title_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_zone_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

TokenAuthReq::~TokenAuthReq() {
  // @@protoc_insertion_point(destructor:zproto.TokenAuthReq)
  SharedDtor();
}

void TokenAuthReq::SharedDtor() {
  app_token_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  device_hash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  device_title_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_zone_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void TokenAuthReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TokenAuthReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TokenAuthReq_descriptor_;
}

const TokenAuthReq& TokenAuthReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_auth_2eproto();
  return *default_instance_;
}

TokenAuthReq* TokenAuthReq::default_instance_ = NULL;

TokenAuthReq* TokenAuthReq::New(::google::protobuf::Arena* arena) const {
  TokenAuthReq* n = new TokenAuthReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TokenAuthReq::Swap(TokenAuthReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TokenAuthReq::InternalSwap(TokenAuthReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata TokenAuthReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TokenAuthReq_descriptor_;
  metadata.reflection = TokenAuthReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TokenAuthReq

// optional int32 app_key = 1;
void TokenAuthReq::clear_app_key() {
  app_key_ = 0;
}
 ::google::protobuf::int32 TokenAuthReq::app_key() const {
  // @@protoc_insertion_point(field_get:zproto.TokenAuthReq.app_key)
  return app_key_;
}
 void TokenAuthReq::set_app_key(::google::protobuf::int32 value) {
  
  app_key_ = value;
  // @@protoc_insertion_point(field_set:zproto.TokenAuthReq.app_key)
}

// optional string app_token = 2;
void TokenAuthReq::clear_app_token() {
  app_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& TokenAuthReq::app_token() const {
  // @@protoc_insertion_point(field_get:zproto.TokenAuthReq.app_token)
  return app_token_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void TokenAuthReq::set_app_token(const ::std::string& value) {
  
  app_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.TokenAuthReq.app_token)
}
 void TokenAuthReq::set_app_token(const char* value) {
  
  app_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.TokenAuthReq.app_token)
}
 void TokenAuthReq::set_app_token(const char* value, size_t size) {
  
  app_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.TokenAuthReq.app_token)
}
 ::std::string* TokenAuthReq::mutable_app_token() {
  
  // @@protoc_insertion_point(field_mutable:zproto.TokenAuthReq.app_token)
  return app_token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* TokenAuthReq::release_app_token() {
  // @@protoc_insertion_point(field_release:zproto.TokenAuthReq.app_token)
  
  return app_token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void TokenAuthReq::set_allocated_app_token(::std::string* app_token) {
  if (app_token != NULL) {
    
  } else {
    
  }
  app_token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), app_token);
  // @@protoc_insertion_point(field_set_allocated:zproto.TokenAuthReq.app_token)
}

// optional bytes device_hash = 3;
void TokenAuthReq::clear_device_hash() {
  device_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& TokenAuthReq::device_hash() const {
  // @@protoc_insertion_point(field_get:zproto.TokenAuthReq.device_hash)
  return device_hash_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void TokenAuthReq::set_device_hash(const ::std::string& value) {
  
  device_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.TokenAuthReq.device_hash)
}
 void TokenAuthReq::set_device_hash(const char* value) {
  
  device_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.TokenAuthReq.device_hash)
}
 void TokenAuthReq::set_device_hash(const void* value, size_t size) {
  
  device_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.TokenAuthReq.device_hash)
}
 ::std::string* TokenAuthReq::mutable_device_hash() {
  
  // @@protoc_insertion_point(field_mutable:zproto.TokenAuthReq.device_hash)
  return device_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* TokenAuthReq::release_device_hash() {
  // @@protoc_insertion_point(field_release:zproto.TokenAuthReq.device_hash)
  
  return device_hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void TokenAuthReq::set_allocated_device_hash(::std::string* device_hash) {
  if (device_hash != NULL) {
    
  } else {
    
  }
  device_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_hash);
  // @@protoc_insertion_point(field_set_allocated:zproto.TokenAuthReq.device_hash)
}

// optional string device_title = 4;
void TokenAuthReq::clear_device_title() {
  device_title_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& TokenAuthReq::device_title() const {
  // @@protoc_insertion_point(field_get:zproto.TokenAuthReq.device_title)
  return device_title_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void TokenAuthReq::set_device_title(const ::std::string& value) {
  
  device_title_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.TokenAuthReq.device_title)
}
 void TokenAuthReq::set_device_title(const char* value) {
  
  device_title_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.TokenAuthReq.device_title)
}
 void TokenAuthReq::set_device_title(const char* value, size_t size) {
  
  device_title_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.TokenAuthReq.device_title)
}
 ::std::string* TokenAuthReq::mutable_device_title() {
  
  // @@protoc_insertion_point(field_mutable:zproto.TokenAuthReq.device_title)
  return device_title_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* TokenAuthReq::release_device_title() {
  // @@protoc_insertion_point(field_release:zproto.TokenAuthReq.device_title)
  
  return device_title_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void TokenAuthReq::set_allocated_device_title(::std::string* device_title) {
  if (device_title != NULL) {
    
  } else {
    
  }
  device_title_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_title);
  // @@protoc_insertion_point(field_set_allocated:zproto.TokenAuthReq.device_title)
}

// optional string time_zone = 5;
void TokenAuthReq::clear_time_zone() {
  time_zone_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& TokenAuthReq::time_zone() const {
  // @@protoc_insertion_point(field_get:zproto.TokenAuthReq.time_zone)
  return time_zone_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void TokenAuthReq::set_time_zone(const ::std::string& value) {
  
  time_zone_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.TokenAuthReq.time_zone)
}
 void TokenAuthReq::set_time_zone(const char* value) {
  
  time_zone_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.TokenAuthReq.time_zone)
}
 void TokenAuthReq::set_time_zone(const char* value, size_t size) {
  
  time_zone_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.TokenAuthReq.time_zone)
}
 ::std::string* TokenAuthReq::mutable_time_zone() {
  
  // @@protoc_insertion_point(field_mutable:zproto.TokenAuthReq.time_zone)
  return time_zone_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* TokenAuthReq::release_time_zone() {
  // @@protoc_insertion_point(field_release:zproto.TokenAuthReq.time_zone)
  
  return time_zone_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void TokenAuthReq::set_allocated_time_zone(::std::string* time_zone) {
  if (time_zone != NULL) {
    
  } else {
    
  }
  time_zone_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), time_zone);
  // @@protoc_insertion_point(field_set_allocated:zproto.TokenAuthReq.time_zone)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AuthRsp::kUserIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AuthRsp::AuthRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.AuthRsp)
}

void AuthRsp::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

AuthRsp::AuthRsp(const AuthRsp& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.AuthRsp)
}

void AuthRsp::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  user_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

AuthRsp::~AuthRsp() {
  // @@protoc_insertion_point(destructor:zproto.AuthRsp)
  SharedDtor();
}

void AuthRsp::SharedDtor() {
  user_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void AuthRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AuthRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AuthRsp_descriptor_;
}

const AuthRsp& AuthRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_auth_2eproto();
  return *default_instance_;
}

AuthRsp* AuthRsp::default_instance_ = NULL;

AuthRsp* AuthRsp::New(::google::protobuf::Arena* arena) const {
  AuthRsp* n = new AuthRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AuthRsp::Swap(AuthRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AuthRsp::InternalSwap(AuthRsp* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata AuthRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AuthRsp_descriptor_;
  metadata.reflection = AuthRsp_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AuthRsp

// optional string user_id = 2;
void AuthRsp::clear_user_id() {
  user_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& AuthRsp::user_id() const {
  // @@protoc_insertion_point(field_get:zproto.AuthRsp.user_id)
  return user_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AuthRsp::set_user_id(const ::std::string& value) {
  
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.AuthRsp.user_id)
}
 void AuthRsp::set_user_id(const char* value) {
  
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.AuthRsp.user_id)
}
 void AuthRsp::set_user_id(const char* value, size_t size) {
  
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.AuthRsp.user_id)
}
 ::std::string* AuthRsp::mutable_user_id() {
  
  // @@protoc_insertion_point(field_mutable:zproto.AuthRsp.user_id)
  return user_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* AuthRsp::release_user_id() {
  // @@protoc_insertion_point(field_release:zproto.AuthRsp.user_id)
  
  return user_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AuthRsp::set_allocated_user_id(::std::string* user_id) {
  if (user_id != NULL) {
    
  } else {
    
  }
  user_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_id);
  // @@protoc_insertion_point(field_set_allocated:zproto.AuthRsp.user_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientOnlineReq::kServerIdFieldNumber;
const int ClientOnlineReq::kConnIdFieldNumber;
const int ClientOnlineReq::kAppIdFieldNumber;
const int ClientOnlineReq::kUserIdFieldNumber;
const int ClientOnlineReq::kStateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientOnlineReq::ClientOnlineReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ClientOnlineReq)
}

void ClientOnlineReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ClientOnlineReq::ClientOnlineReq(const ClientOnlineReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.ClientOnlineReq)
}

void ClientOnlineReq::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  server_id_ = 0u;
  conn_id_ = GOOGLE_ULONGLONG(0);
  app_id_ = 0u;
  user_id_ = 0u;
  state_ = 0u;
}

ClientOnlineReq::~ClientOnlineReq() {
  // @@protoc_insertion_point(destructor:zproto.ClientOnlineReq)
  SharedDtor();
}

void ClientOnlineReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ClientOnlineReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientOnlineReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClientOnlineReq_descriptor_;
}

const ClientOnlineReq& ClientOnlineReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_auth_2eproto();
  return *default_instance_;
}

ClientOnlineReq* ClientOnlineReq::default_instance_ = NULL;

ClientOnlineReq* ClientOnlineReq::New(::google::protobuf::Arena* arena) const {
  ClientOnlineReq* n = new ClientOnlineReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ClientOnlineReq::Swap(ClientOnlineReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientOnlineReq::InternalSwap(ClientOnlineReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ClientOnlineReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClientOnlineReq_descriptor_;
  metadata.reflection = ClientOnlineReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ClientOnlineReq

// optional uint32 server_id = 1;
void ClientOnlineReq::clear_server_id() {
  server_id_ = 0u;
}
 ::google::protobuf::uint32 ClientOnlineReq::server_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOnlineReq.server_id)
  return server_id_;
}
 void ClientOnlineReq::set_server_id(::google::protobuf::uint32 value) {
  
  server_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOnlineReq.server_id)
}

// optional uint64 conn_id = 2;
void ClientOnlineReq::clear_conn_id() {
  conn_id_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 ClientOnlineReq::conn_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOnlineReq.conn_id)
  return conn_id_;
}
 void ClientOnlineReq::set_conn_id(::google::protobuf::uint64 value) {
  
  conn_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOnlineReq.conn_id)
}

// optional uint32 app_id = 3;
void ClientOnlineReq::clear_app_id() {
  app_id_ = 0u;
}
 ::google::protobuf::uint32 ClientOnlineReq::app_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOnlineReq.app_id)
  return app_id_;
}
 void ClientOnlineReq::set_app_id(::google::protobuf::uint32 value) {
  
  app_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOnlineReq.app_id)
}

// optional uint32 user_id = 4;
void ClientOnlineReq::clear_user_id() {
  user_id_ = 0u;
}
 ::google::protobuf::uint32 ClientOnlineReq::user_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOnlineReq.user_id)
  return user_id_;
}
 void ClientOnlineReq::set_user_id(::google::protobuf::uint32 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOnlineReq.user_id)
}

// optional uint32 state = 5;
void ClientOnlineReq::clear_state() {
  state_ = 0u;
}
 ::google::protobuf::uint32 ClientOnlineReq::state() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOnlineReq.state)
  return state_;
}
 void ClientOnlineReq::set_state(::google::protobuf::uint32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOnlineReq.state)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientOnlineRsp::kIndexIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientOnlineRsp::ClientOnlineRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ClientOnlineRsp)
}

void ClientOnlineRsp::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ClientOnlineRsp::ClientOnlineRsp(const ClientOnlineRsp& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.ClientOnlineRsp)
}

void ClientOnlineRsp::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  index_id_ = GOOGLE_ULONGLONG(0);
}

ClientOnlineRsp::~ClientOnlineRsp() {
  // @@protoc_insertion_point(destructor:zproto.ClientOnlineRsp)
  SharedDtor();
}

void ClientOnlineRsp::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ClientOnlineRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientOnlineRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClientOnlineRsp_descriptor_;
}

const ClientOnlineRsp& ClientOnlineRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_auth_2eproto();
  return *default_instance_;
}

ClientOnlineRsp* ClientOnlineRsp::default_instance_ = NULL;

ClientOnlineRsp* ClientOnlineRsp::New(::google::protobuf::Arena* arena) const {
  ClientOnlineRsp* n = new ClientOnlineRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ClientOnlineRsp::Swap(ClientOnlineRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientOnlineRsp::InternalSwap(ClientOnlineRsp* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ClientOnlineRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClientOnlineRsp_descriptor_;
  metadata.reflection = ClientOnlineRsp_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ClientOnlineRsp

// optional uint64 index_id = 1;
void ClientOnlineRsp::clear_index_id() {
  index_id_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 ClientOnlineRsp::index_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOnlineRsp.index_id)
  return index_id_;
}
 void ClientOnlineRsp::set_index_id(::google::protobuf::uint64 value) {
  
  index_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOnlineRsp.index_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientOfflineReq::kServerIdFieldNumber;
const int ClientOfflineReq::kConnIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientOfflineReq::ClientOfflineReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ClientOfflineReq)
}

void ClientOfflineReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ClientOfflineReq::ClientOfflineReq(const ClientOfflineReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.ClientOfflineReq)
}

void ClientOfflineReq::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  server_id_ = 0u;
  conn_id_ = GOOGLE_ULONGLONG(0);
}

ClientOfflineReq::~ClientOfflineReq() {
  // @@protoc_insertion_point(destructor:zproto.ClientOfflineReq)
  SharedDtor();
}

void ClientOfflineReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ClientOfflineReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientOfflineReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClientOfflineReq_descriptor_;
}

const ClientOfflineReq& ClientOfflineReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_auth_2eproto();
  return *default_instance_;
}

ClientOfflineReq* ClientOfflineReq::default_instance_ = NULL;

ClientOfflineReq* ClientOfflineReq::New(::google::protobuf::Arena* arena) const {
  ClientOfflineReq* n = new ClientOfflineReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ClientOfflineReq::Swap(ClientOfflineReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientOfflineReq::InternalSwap(ClientOfflineReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ClientOfflineReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClientOfflineReq_descriptor_;
  metadata.reflection = ClientOfflineReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ClientOfflineReq

// optional uint32 server_id = 1;
void ClientOfflineReq::clear_server_id() {
  server_id_ = 0u;
}
 ::google::protobuf::uint32 ClientOfflineReq::server_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOfflineReq.server_id)
  return server_id_;
}
 void ClientOfflineReq::set_server_id(::google::protobuf::uint32 value) {
  
  server_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOfflineReq.server_id)
}

// optional uint64 conn_id = 2;
void ClientOfflineReq::clear_conn_id() {
  conn_id_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 ClientOfflineReq::conn_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOfflineReq.conn_id)
  return conn_id_;
}
 void ClientOfflineReq::set_conn_id(::google::protobuf::uint64 value) {
  
  conn_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOfflineReq.conn_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientOfflineRsp::kIndexIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientOfflineRsp::ClientOfflineRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ClientOfflineRsp)
}

void ClientOfflineRsp::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ClientOfflineRsp::ClientOfflineRsp(const ClientOfflineRsp& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.ClientOfflineRsp)
}

void ClientOfflineRsp::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  index_id_ = GOOGLE_ULONGLONG(0);
}

ClientOfflineRsp::~ClientOfflineRsp() {
  // @@protoc_insertion_point(destructor:zproto.ClientOfflineRsp)
  SharedDtor();
}

void ClientOfflineRsp::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ClientOfflineRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientOfflineRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClientOfflineRsp_descriptor_;
}

const ClientOfflineRsp& ClientOfflineRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_auth_2eproto();
  return *default_instance_;
}

ClientOfflineRsp* ClientOfflineRsp::default_instance_ = NULL;

ClientOfflineRsp* ClientOfflineRsp::New(::google::protobuf::Arena* arena) const {
  ClientOfflineRsp* n = new ClientOfflineRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ClientOfflineRsp::Swap(ClientOfflineRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientOfflineRsp::InternalSwap(ClientOfflineRsp* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ClientOfflineRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClientOfflineRsp_descriptor_;
  metadata.reflection = ClientOfflineRsp_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ClientOfflineRsp

// optional uint64 index_id = 1;
void ClientOfflineRsp::clear_index_id() {
  index_id_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 ClientOfflineRsp::index_id() const {
  // @@protoc_insertion_point(field_get:zproto.ClientOfflineRsp.index_id)
  return index_id_;
}
 void ClientOfflineRsp::set_index_id(::google::protobuf::uint64 value) {
  
  index_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.ClientOfflineRsp.index_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace zproto

// @@protoc_insertion_point(global_scope)
