// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zrpc_test.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "zrpc_test.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace zproto {

namespace {

const ::google::protobuf::Descriptor* ZRpcTestReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ZRpcTestReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* ZRpcTestRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ZRpcTestRsp_reflection_ = NULL;
const ::google::protobuf::Descriptor* ZRpcTestPush_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ZRpcTestPush_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_zrpc_5ftest_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_zrpc_5ftest_2eproto() {
  protobuf_AddDesc_zrpc_5ftest_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "zrpc_test.proto");
  GOOGLE_CHECK(file != NULL);
  ZRpcTestReq_descriptor_ = file->message_type(0);
  static const int ZRpcTestReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZRpcTestReq, req_id_),
  };
  ZRpcTestReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ZRpcTestReq_descriptor_,
      ZRpcTestReq::default_instance_,
      ZRpcTestReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(ZRpcTestReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZRpcTestReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZRpcTestReq, _is_default_instance_));
  ZRpcTestRsp_descriptor_ = file->message_type(1);
  static const int ZRpcTestRsp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZRpcTestRsp, rsp_data_),
  };
  ZRpcTestRsp_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ZRpcTestRsp_descriptor_,
      ZRpcTestRsp::default_instance_,
      ZRpcTestRsp_offsets_,
      -1,
      -1,
      -1,
      sizeof(ZRpcTestRsp),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZRpcTestRsp, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZRpcTestRsp, _is_default_instance_));
  ZRpcTestPush_descriptor_ = file->message_type(2);
  static const int ZRpcTestPush_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZRpcTestPush, push_data_),
  };
  ZRpcTestPush_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ZRpcTestPush_descriptor_,
      ZRpcTestPush::default_instance_,
      ZRpcTestPush_offsets_,
      -1,
      -1,
      -1,
      sizeof(ZRpcTestPush),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZRpcTestPush, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZRpcTestPush, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_zrpc_5ftest_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ZRpcTestReq_descriptor_, &ZRpcTestReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ZRpcTestRsp_descriptor_, &ZRpcTestRsp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ZRpcTestPush_descriptor_, &ZRpcTestPush::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_zrpc_5ftest_2eproto() {
  delete ZRpcTestReq::default_instance_;
  delete ZRpcTestReq_reflection_;
  delete ZRpcTestRsp::default_instance_;
  delete ZRpcTestRsp_reflection_;
  delete ZRpcTestPush::default_instance_;
  delete ZRpcTestPush_reflection_;
}

void protobuf_AddDesc_zrpc_5ftest_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_zrpc_5ftest_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017zrpc_test.proto\022\006zproto\"\035\n\013ZRpcTestReq"
    "\022\016\n\006req_id\030\001 \001(\t\"\037\n\013ZRpcTestRsp\022\020\n\010rsp_d"
    "ata\030\001 \001(\t\"!\n\014ZRpcTestPush\022\021\n\tpush_data\030\001"
    " \001(\tB#\n\027com.zchat.engine.zprotoB\006ZProtoH"
    "\002b\006proto3", 169);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "zrpc_test.proto", &protobuf_RegisterTypes);
  ZRpcTestReq::default_instance_ = new ZRpcTestReq();
  ZRpcTestRsp::default_instance_ = new ZRpcTestRsp();
  ZRpcTestPush::default_instance_ = new ZRpcTestPush();
  ZRpcTestReq::default_instance_->InitAsDefaultInstance();
  ZRpcTestRsp::default_instance_->InitAsDefaultInstance();
  ZRpcTestPush::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_zrpc_5ftest_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_zrpc_5ftest_2eproto {
  StaticDescriptorInitializer_zrpc_5ftest_2eproto() {
    protobuf_AddDesc_zrpc_5ftest_2eproto();
  }
} static_descriptor_initializer_zrpc_5ftest_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ZRpcTestReq::kReqIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ZRpcTestReq::ZRpcTestReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ZRpcTestReq)
}

void ZRpcTestReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ZRpcTestReq::ZRpcTestReq(const ZRpcTestReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.ZRpcTestReq)
}

void ZRpcTestReq::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  req_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ZRpcTestReq::~ZRpcTestReq() {
  // @@protoc_insertion_point(destructor:zproto.ZRpcTestReq)
  SharedDtor();
}

void ZRpcTestReq::SharedDtor() {
  req_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void ZRpcTestReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ZRpcTestReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ZRpcTestReq_descriptor_;
}

const ZRpcTestReq& ZRpcTestReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_zrpc_5ftest_2eproto();
  return *default_instance_;
}

ZRpcTestReq* ZRpcTestReq::default_instance_ = NULL;

ZRpcTestReq* ZRpcTestReq::New(::google::protobuf::Arena* arena) const {
  ZRpcTestReq* n = new ZRpcTestReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ZRpcTestReq::Swap(ZRpcTestReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ZRpcTestReq::InternalSwap(ZRpcTestReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ZRpcTestReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ZRpcTestReq_descriptor_;
  metadata.reflection = ZRpcTestReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ZRpcTestReq

// optional string req_id = 1;
void ZRpcTestReq::clear_req_id() {
  req_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& ZRpcTestReq::req_id() const {
  // @@protoc_insertion_point(field_get:zproto.ZRpcTestReq.req_id)
  return req_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ZRpcTestReq::set_req_id(const ::std::string& value) {
  
  req_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.ZRpcTestReq.req_id)
}
 void ZRpcTestReq::set_req_id(const char* value) {
  
  req_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.ZRpcTestReq.req_id)
}
 void ZRpcTestReq::set_req_id(const char* value, size_t size) {
  
  req_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.ZRpcTestReq.req_id)
}
 ::std::string* ZRpcTestReq::mutable_req_id() {
  
  // @@protoc_insertion_point(field_mutable:zproto.ZRpcTestReq.req_id)
  return req_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ZRpcTestReq::release_req_id() {
  // @@protoc_insertion_point(field_release:zproto.ZRpcTestReq.req_id)
  
  return req_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ZRpcTestReq::set_allocated_req_id(::std::string* req_id) {
  if (req_id != NULL) {
    
  } else {
    
  }
  req_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), req_id);
  // @@protoc_insertion_point(field_set_allocated:zproto.ZRpcTestReq.req_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ZRpcTestRsp::kRspDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ZRpcTestRsp::ZRpcTestRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ZRpcTestRsp)
}

void ZRpcTestRsp::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ZRpcTestRsp::ZRpcTestRsp(const ZRpcTestRsp& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.ZRpcTestRsp)
}

void ZRpcTestRsp::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  rsp_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ZRpcTestRsp::~ZRpcTestRsp() {
  // @@protoc_insertion_point(destructor:zproto.ZRpcTestRsp)
  SharedDtor();
}

void ZRpcTestRsp::SharedDtor() {
  rsp_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void ZRpcTestRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ZRpcTestRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ZRpcTestRsp_descriptor_;
}

const ZRpcTestRsp& ZRpcTestRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_zrpc_5ftest_2eproto();
  return *default_instance_;
}

ZRpcTestRsp* ZRpcTestRsp::default_instance_ = NULL;

ZRpcTestRsp* ZRpcTestRsp::New(::google::protobuf::Arena* arena) const {
  ZRpcTestRsp* n = new ZRpcTestRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ZRpcTestRsp::Swap(ZRpcTestRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ZRpcTestRsp::InternalSwap(ZRpcTestRsp* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ZRpcTestRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ZRpcTestRsp_descriptor_;
  metadata.reflection = ZRpcTestRsp_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ZRpcTestRsp

// optional string rsp_data = 1;
void ZRpcTestRsp::clear_rsp_data() {
  rsp_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& ZRpcTestRsp::rsp_data() const {
  // @@protoc_insertion_point(field_get:zproto.ZRpcTestRsp.rsp_data)
  return rsp_data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ZRpcTestRsp::set_rsp_data(const ::std::string& value) {
  
  rsp_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.ZRpcTestRsp.rsp_data)
}
 void ZRpcTestRsp::set_rsp_data(const char* value) {
  
  rsp_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.ZRpcTestRsp.rsp_data)
}
 void ZRpcTestRsp::set_rsp_data(const char* value, size_t size) {
  
  rsp_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.ZRpcTestRsp.rsp_data)
}
 ::std::string* ZRpcTestRsp::mutable_rsp_data() {
  
  // @@protoc_insertion_point(field_mutable:zproto.ZRpcTestRsp.rsp_data)
  return rsp_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ZRpcTestRsp::release_rsp_data() {
  // @@protoc_insertion_point(field_release:zproto.ZRpcTestRsp.rsp_data)
  
  return rsp_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ZRpcTestRsp::set_allocated_rsp_data(::std::string* rsp_data) {
  if (rsp_data != NULL) {
    
  } else {
    
  }
  rsp_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), rsp_data);
  // @@protoc_insertion_point(field_set_allocated:zproto.ZRpcTestRsp.rsp_data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ZRpcTestPush::kPushDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ZRpcTestPush::ZRpcTestPush()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ZRpcTestPush)
}

void ZRpcTestPush::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ZRpcTestPush::ZRpcTestPush(const ZRpcTestPush& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.ZRpcTestPush)
}

void ZRpcTestPush::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  push_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ZRpcTestPush::~ZRpcTestPush() {
  // @@protoc_insertion_point(destructor:zproto.ZRpcTestPush)
  SharedDtor();
}

void ZRpcTestPush::SharedDtor() {
  push_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void ZRpcTestPush::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ZRpcTestPush::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ZRpcTestPush_descriptor_;
}

const ZRpcTestPush& ZRpcTestPush::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_zrpc_5ftest_2eproto();
  return *default_instance_;
}

ZRpcTestPush* ZRpcTestPush::default_instance_ = NULL;

ZRpcTestPush* ZRpcTestPush::New(::google::protobuf::Arena* arena) const {
  ZRpcTestPush* n = new ZRpcTestPush;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ZRpcTestPush::Swap(ZRpcTestPush* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ZRpcTestPush::InternalSwap(ZRpcTestPush* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ZRpcTestPush::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ZRpcTestPush_descriptor_;
  metadata.reflection = ZRpcTestPush_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ZRpcTestPush

// optional string push_data = 1;
void ZRpcTestPush::clear_push_data() {
  push_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& ZRpcTestPush::push_data() const {
  // @@protoc_insertion_point(field_get:zproto.ZRpcTestPush.push_data)
  return push_data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ZRpcTestPush::set_push_data(const ::std::string& value) {
  
  push_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.ZRpcTestPush.push_data)
}
 void ZRpcTestPush::set_push_data(const char* value) {
  
  push_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.ZRpcTestPush.push_data)
}
 void ZRpcTestPush::set_push_data(const char* value, size_t size) {
  
  push_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.ZRpcTestPush.push_data)
}
 ::std::string* ZRpcTestPush::mutable_push_data() {
  
  // @@protoc_insertion_point(field_mutable:zproto.ZRpcTestPush.push_data)
  return push_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ZRpcTestPush::release_push_data() {
  // @@protoc_insertion_point(field_release:zproto.ZRpcTestPush.push_data)
  
  return push_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ZRpcTestPush::set_allocated_push_data(::std::string* push_data) {
  if (push_data != NULL) {
    
  } else {
    
  }
  push_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), push_data);
  // @@protoc_insertion_point(field_set_allocated:zproto.ZRpcTestPush.push_data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace zproto

// @@protoc_insertion_point(global_scope)
